### ISSUE TITLE
comments are not clearly visible anymore in current version

### ISSUE THREAD

**Issue by qbicStefanC** [qbicsoftware/metadata-doc#1]
Hi
Somehow with the current version the comments are not clearly visible anymore, e.g. when I compare it to version 1.0 where I had nice white fields behind the comments.

How is if for others?

**Comment by mGauder** [comment]
I cannot reproduce your error. When I am downloading the file, I am still able to see the comments.

**Comment by subwaystation** [comment]
I took a look at [https://github.com/qbicsoftware/metadata-doc/blob/master/metadata-doc-1.0.0.xls](https://github.com/qbicsoftware/metadata-doc/blob/master/metadata-doc-1.0.0.xls) and this one works for me both on Linux and the WindowsVM.

**Comment by mGauder** [comment]
Perfect, thanks for testing. Then we will go forward with the XLS format from now on.
