### ISSUE TITLE
Change of the "NGS_Metadata_Sheet" to integrate biosafety information

### ISSUE THREAD

**Issue by nicolascasadei** [qbicsoftware/metadata-doc#10]
To simplify the compliance in reporting samples biosafety available in the laboratory, as well as to improve the reporting of biohazards, we would like to ask the users to add new information on the sample sheets.

A request is currently pending at our biosafety comitee. 

Best, Nicolas

**Comment by qbicStefanC** [comment]
a column for biosafety level was added to the new metadata sheet (adressed in branch  `update_metadata_sheet_April2022`. I leave it open until it is clearly solved

**Comment by qbicStefanC** [comment]
That is now solved with the current master version.
