### ISSUE TITLE
providing the instructions from google drive and in a more specific manner

### ISSUE THREAD

**Issue by nicolascasadei** [qbicsoftware/metadata-doc#11]
We have currently on the first tab some recommendation concerning the shipment and requierement of samples. This information is overall correct but for specific protocols not detailed enough. 

To avoid having multiple documentation which might not be consistant, I would prefer document in a larger amount of details the requierement using another tool (like google drive) and remove this tab from our sample sheet.

Nicolas

**Comment by qbicStefanC** [comment]
That is solved with the current version. The sample shipment requierements were removed from the excel template and are now accessible via the NCCT website/ gdrive only.
