### ISSUE TITLE
Change of the "NGS_Metadata_Sheet" to integrate batches

### ISSUE THREAD

**Issue by jenmuell** [qbicsoftware/metadata-doc#12]
A new column “batch_number” should be added to the NGS_Metadata_Sheet. The customer will be able to indicate which samples should be processed together and it would also be possible to prioritize batches over that column.
Thank you and best wishes!
Jenny and Max

**Comment by nicolascasadei** [comment]
Hello, just a small up as this would help us to continue progressing in the project. 

It is only adding one column to the document and uploading the new version.

Cheers, Nicolas

**Comment by qbicStefanC** [comment]
Solved now with new branch `update_metadata_sheet_April2022`.
