### ISSUE TITLE
COVID-19 Microbiology Metadata Sheet

### ISSUE THREAD

**Issue by angelovangel** [qbicsoftware/metadata-doc#3]
Hi Marie,
the sample sheet has quite a lot of fields, which may confuse the customers.
I think all of them are relevant and good to have, but may be under Instructions you can state which fields are obligatory and also mark those in the "samples" sheet. Also, examples for each field would make it easier to fill. For us, obligatory are:

- sample name
- sample source (e.g. human, air filter, furniture surface...)
- sample tissue (e.g. naso-pharyngeal swab)
- country
- city
- sampling date (date of sampling, e.g. when the swab was taken)
- collecting institution (collected and eventually isolated nucleic acid from the sample)
- Covid 19 Ct test result

All of these are already present, except **sampling date** - this is essential for submission to GISAID.

Best,
Angel

**Comment by ghost** [comment]
Hi Angel,

sorry for the late reply and thank you for your valuable feedback!
Yes, I already discussed this with Michael and I will include the changes beginning of next week (I am acutally on vacation today).

Thanks and best, 
Marie
