### ISSUE TITLE
Improvement in the customer info tab

### ISSUE THREAD

**Issue by nicolascasadei** [qbicsoftware/metadata-doc#5]
As we are also using this sample sheet for DFG / intern / extern project, there is a few informations that are not really clear for users:

Contact details:
"Company name" is missing
"Name of Head" by "Name of Project leader"
"Name" by "Direct contact for this project"

Accounting:
"DFG proposal" should be complemented by "quote number" like "DFG proposal or quote number"
"Kostenstelle" and "Drittelnummer" should be only filled for Tübingen project. Thus I propose "Kostenstelle for UKT and uni Tübingen only"; "Drittelnummer for UKT and uni Tübingen only"

Any comments are welcome

Nicolas

**Comment by ghost** [comment]
Hi @nicolascasadei,

thanks for your feedback!
I will apply the proposed changes and make a new release asap.

Best,
Marie

**Comment by ghost** [comment]
Fixed in new versions.
