### ISSUE TITLE
Metadata sheet IMGAG and MiBi

### ISSUE THREAD

**Issue by nicolascasadei** [qbicsoftware/metadata-doc#6]
Overall I think that it is good to have 2 sample sheet for the both institute as it also make more clear who received the samples. 

I would try to limit the difference only to the Instructions sheet to make sure that we do not develop two divergent documentation.

If you would agree, we need a solution for the customer info where we specify that the sheets should also be sent per email. I would then propose to put this info in the instructions tab, despite we are aware that this sheet in not always read by the users.

Any suggestion is welcome

Nicolas

**Comment by ghost** [comment]
Hi @nicolascasadei,

> I would try to limit the difference only to the Instructions sheet to make sure that we do not develop two divergent documentation.

This is already in place/handled and two different metadata sheets exist for IMGAG (NGS) and the Mibi (Microbiology).


> If you would agree, we need a solution for the customer info where we specify that the sheets should also be sent per email. I would then propose to put this info in the instructions tab, despite we are aware that this sheet in not always read by the users.

This is also already accounted for in the tab "Customer Info". At the very top the customer is asked to please send this sheet via email/Zendesk, and also attach a printed version to the samples, too.

Hope this helps!

Best,
Marie
